name: update3

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update3:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node update3.js

      - name: Commit changes
        run: |
          git config --global user.name "stream-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add streams3/*.m3u8
          git commit -m "Auto update streams" || echo "No changes"
          git pull origin main --rebase || echo "No rebase needed"
          git push
